### ISSUE TITLE
Twig 1.18 breaks assetic config?

### ISSUE THREAD

**Issue by XWB** [twigphp/Twig#1611]
Say we have this config:

```yml
assetic:
    assets:
        jquery_ui_core:
            inputs:
                - '@MyBundle/Resources/js/jquery.ui.core.js
                - '@MyBundle/Resources/js/jquery.ui.widget.js
                - '@MyBundle/Resources/js/jquery.ui.mouse.js
                - '@MyBundle/Resources/js/jquery.ui.position.js
```

Now we can do something like this:

```twig
{% javascripts
    '@jquery_ui_core'
%}
<script src="{{ asset_url }}"></script>
{% endjavascripts %}
```

Upgrading to Twig 1.18 and removing the app cache leads to the following error:

```
An exception has been thrown during the compilation of a template ("Warning: Invalid argument supplied for foreach()") in "test.html.twig".

ContextErrorException: Warning: Invalid argument supplied for foreach() in MyApp/cache/dev/classes.php at line 1635

1632 }
1633 $filepaths[] = $file;
1634 }
1635 foreach ($this->paths as $path) {
1636 if (file_exists($file = $path.DIRECTORY_SEPARATOR.$name)) {
1637 if (true === $first) {
1638 return $file;
```

Reverting back to Twig 1.17 and everything works again. Thoughts?
