### ISSUE TITLE
Minor design issue in Twig docs page

### ISSUE THREAD

**Issue by javiereguiluz** [twigphp/Twig#2373]
At the bottom of this page: http://twig.sensiolabs.org/doc/2.x/

![twig-reference-error](https://cloud.githubusercontent.com/assets/73419/22185196/a3d4e218-e0e1-11e6-97be-49a83c144fda.png)

This can be solved by changing this CSS style:

```css
.builtin-reference {
    min-width: 120px;
    float: left;
    padding-right: 60px; /* <--------- THIS IS THE ERROR */
    padding-bottom: 20px;
}
```

Instead of `60px`, use `54px` or less.
