### ISSUE TITLE
[twig-extra-bundle] markdown_to_html: Passing configuration to League\CommonMark\CommonMarkConverter

### ISSUE THREAD

**Issue by Dasug** [twigphp/Twig#3725]
I'm using the twig extra bundle's ``markdown_to_html`` filter on Symfony 6.1 with League/CommonMark as the markdown parser library.

The library has a few configuration options that can be passed to the ``CommonMarkConverter`` constructor and cannot be adjusted after the ``CommonMarkConverter`` object has been constructed. See https://commonmark.thephpleague.com/2.3/configuration/

Currently however, the ``LeagueCommonMarkConverterFactory`` class seems to call the ``CommonMarkConverter`` without any parameters: https://github.com/twigphp/Twig/blob/3cefebac2bdc754031578a50732dd7ffdd09bfec/extra/twig-extra-bundle/LeagueCommonMarkConverterFactory.php#L34

Is there therefore currently no simple way to pass configuration to the library or have I missed something obvious?

I have been able to bypass the factory class by manually declaring the ``CommonMarkConverter`` constructor arguments in the ``services.yaml`` file as such:
```yaml
League\CommonMark\CommonMarkConverter:
    arguments:
        $config: {allow_unsafe_links: false}

twig.markdown.league_common_mark_converter:
    alias: League\CommonMark\CommonMarkConverter
```
However as this bypasses the Factory class I then lose the capability of including any CommonMark extensions.
